### ISSUE TITLE
Suggest of using Vulners Linux Audit API

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble-salt#54]
_From @vulnersCom on September 22, 2016 17:17_

Hi!
Thanks for using our DB, at first.
We release Linux Audit API and it will be very cool, if you will add it :)

It provides API for vulnerability scan.
As input it takes "rpm -qa" for RPM based systems and "dpkg-query -W -f='${Package} ${Version} ${Architecture}\n'" for Debian family.

GUI is here: https://vulners.com/#audit
Description here: https://blog.vulners.com/linux-vulnerability-audit-in-vulners/
And sample here with OS version detection: https://github.com/videns/vulners-scanner

It's extremely fast (~160ms) for checking 500-600 packages.
Hope, it will be usefull.

_Copied from original issue: hubblestack/nova#255_

**Comment by basepi** [comment]
Very cool! We'll look into getting it added.

**Comment by basepi** [comment]
_From @vulnersCom on November 9, 2016 13:12_

Hello, fellows!
We see a lot of  /api/v3/archive/distributive/ calls at our serverside.
So, just as gentle reminder, maybe we will switch to much more traffic economy /api/v3/audit API? :)

**Comment by basepi** [comment]
Hehe, thanks for the reminder @vulnersCom. We definitely need to do that. Sorry for the increased traffic! :)

**Comment by basepi** [comment]
_From @vulnersCom on November 10, 2016 8:56_

No a problem)) We are glad to be useful))
If there will be any issues with audit API feel free to ask me.

**Comment by basepi** [comment]
_From @vulnersCom on November 23, 2016 16:5_

Hi, guys! Any help maybe ?)

**Comment by basepi** [comment]
_From @avb76 on November 23, 2016 16:28_

@vulnersCom, I will take a look over this during the next period! Maybe then :)

**Comment by basepi** [comment]
_From @vulnersCom on January 8, 2017 15:38_

Gentle Ping :)

**Comment by vulnersCom** [comment]
Hi, fellows! 👍 
How about tuning?))

**Comment by basepi** [comment]
@avb76 any progress on this?

**Comment by avb76** [comment]
Work in progress. I hope it will be completed by the end of the week.

**Comment by basepi** [comment]
Fixed in #61
