### ISSUE TITLE
rhels-7-level-1-scored-v1.yaml requires both rsyslog and syslog-ng to be installed

### ISSUE THREAD

**Issue by lilmansplace** [hubblestack/hubble-salt#71]
salt-call hubble.top
....
Failure:
        |_
          ----------
          CIS-4.2.3:
              Ensure rsyslog or syslog-ng is installed
....
yet when I run:
rpm -qa | grep syslog
rsyslog-7.4.7-16.el7.x86_64

Once i've installed syslog-ng
rpm -qa | grep syslog
rsyslog-7.4.7-16.el7.x86_64
syslog-ng-libdbi-3.5.6-3.el7.x86_64

Both are now installed and the Failure is now a success
salt-call hubble.top
....
Success:
        |_
          ----------
          CIS-4.2.3:
              Ensure rsyslog or syslog-ng is installed

I don't think the point was that you need twice the log forwarders to be compliant.  Can this or become and actual or not an and.

Thanks!

**Comment by basepi** [comment]
We definitely need to make this an `or`. Thanks for the report!

**Comment by basepi** [comment]
This issue was moved to hubblestack/hubble#90
