### ISSUE TITLE
Specifying a non-existent profile should return message

### ISSUE THREAD

**Issue by absolutejam** [hubblestack/hubble-salt#75]
To avoid confusion, when specifying a profile that doesn't exist on the target (either not synced, typo'd, etc.), a message should be returned explicitly stating so, instead of returning blank results.

`salt 'minion' hubble.audit myfake.profile`

Current:
```
minion
    ----------
    Failure:
    Success:
```

Suggested:
```
minion
    profile 'myfake.profile' is not available.
```

The suggested message emulates the message for missing modules.

**Comment by basepi** [comment]
I very much agree, I didn't realize we weren't returning any sort of error if no profile was found.
